import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { cacheDirectory, copyAsync, documentDirectory } from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, Pressable, ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText, ThemedView } from '@/src/components/shared';
import { getGroupById } from '@/src/libs/constants';

export default function SettleTripScreen() {
    const { id } = useLocalSearchParams<{ id: string }>();
    const group = getGroupById(id);
    const handleBack = () => {
        if (router.canGoBack && router.canGoBack()) {
            router.back();
        } else {
            router.push('/');
        }
    };

    const buildStatusReportHtml = () => `
    <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 24px; }
          h1 { color: #111827; }
          p { color: #374151; }
          .card { border: 1px solid #E5E7EB; border-radius: 16px; padding: 16px; margin-top: 16px; }
          .row { display: flex; justify-content: space-between; margin-bottom: 8px; }
          .muted { color: #6B7280; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${group?.name ?? 'Group'} · Status report</h1>
        <p>Destination: ${group?.destination}</p>
        <div class="card">
          <div class="row"><strong>Total expenses</strong><span>$${group?.totalExpense.toFixed(2)}</span></div>
          <div class="row"><strong>Your share</strong><span>$${group?.yourShare.toFixed(2)}</span></div>
          <div class="muted">Generated by Trip Splitter</div>
        </div>
        <div class="card">
          <strong>Stats</strong>
          ${(group?.stats ?? [])
            .map((stat) => `<div class="row"><span>${stat.label}</span><span>${stat.value}</span></div>`)
            .join('')}
        </div>
      </body>
    </html>
  `;

    const handleStatusReport = async (action: 'share' | 'save') => {
        if (!group) return;
        try {
            const html = buildStatusReportHtml();
            const { uri } = await Print.printToFileAsync({ html });

            if (action === 'share') {
                if (!(await Sharing.isAvailableAsync())) {
                    Alert.alert('Sharing unavailable', 'A sharing sheet is not available on this device.');
                    return;
                }
                await Sharing.shareAsync(uri);
            } else {
                const baseDir = documentDirectory ?? cacheDirectory ?? '';
                const target = `${baseDir}trip-splitter-status-${group.id}.pdf`;
                await copyAsync({ from: uri, to: target });
                Alert.alert('Saved', 'PDF report saved to your documents folder.', [
                    { text: 'OK' },
                ]);
            }
        } catch (error) {
            console.error('Status report error', error);
            Alert.alert('Something went wrong', 'Unable to generate the report right now.');
        }
    };

    if (!group) {
        return (
            <ThemedView className="flex-1 items-center justify-center gap-4 p-5">
                <ThemedText type="subtitle">Group not found</ThemedText>
                <Pressable className="rounded-full bg-sky-500 px-6 py-3" onPress={handleBack}>
                    <ThemedText className="text-white font-semibold">Go back</ThemedText>
                </Pressable>
            </ThemedView>
        );
    }

    return (
        <ThemedView className="flex-1">
            <SafeAreaView className="flex-1">
                <ScrollView contentContainerClassName="gap-5 p-5 pb-10" showsVerticalScrollIndicator={false}>
                    <View className="flex-row items-center justify-between">
                        <Pressable className="h-10 w-10 items-center justify-center rounded-xl bg-gray-100" onPress={handleBack}>
                            <MaterialIcons name="arrow-back-ios-new" size={18} color="#111827" />
                        </Pressable>
                        <ThemedText type="subtitle">SettleTrip</ThemedText>
                        <View className="rounded-full bg-gray-100 px-3 py-1">
                            <ThemedText className="text-gray-600 font-semibold">{group.members.length}</ThemedText>
                        </View>
                    </View>

                    <View className="gap-3 rounded-3xl bg-white p-6 shadow shadow-black/10">
                        <ThemedText type="title">Settle up with confidence</ThemedText>
                        <ThemedText className="text-gray-500">
                            Generate smart recommendations and reports to help everyone settle their share quickly.
                        </ThemedText>
                    </View>

                    <View className="gap-4">
                        <Pressable
                            className="gap-3 rounded-2xl bg-white p-5 shadow shadow-black/10"
                            onPress={() => router.push(`/group/${group.id}/equalization`)}>
                            <View className="flex-row items-center gap-3">
                                <View className="h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50">
                                    <MaterialIcons name="compare-arrows" size={22} color="#059669" />
                                </View>
                                <View>
                                    <ThemedText type="defaultSemiBold">Equalization payments</ThemedText>
                                    <ThemedText className="text-gray-500">Smart suggestions to balance the ledger</ThemedText>
                                </View>
                            </View>
                            <View className="flex-row items-center justify-between">
                                <ThemedText className="text-gray-500">Review payment plan</ThemedText>
                                <MaterialIcons name="chevron-right" size={20} color="#111827" />
                            </View>
                        </Pressable>

                        <View className="gap-3 rounded-2xl bg-white p-5 shadow shadow-black/10">
                            <View className="flex-row items-center gap-3">
                                <View className="h-12 w-12 items-center justify-center rounded-2xl bg-blue-50">
                                    <MaterialIcons name="summarize" size={22} color="#0EA5E9" />
                                </View>
                                <View>
                                    <ThemedText type="defaultSemiBold">Status report</ThemedText>
                                    <ThemedText className="text-gray-500">Detailed view of who owes whom</ThemedText>
                                </View>
                            </View>
                            <View className="flex-row gap-2">
                                <Pressable
                                    className="flex-1 flex-row items-center justify-center gap-2 rounded-2xl bg-gray-100 py-3"
                                    onPress={() => handleStatusReport('share')}>
                                    <MaterialIcons name="ios-share" size={18} color="#111827" />
                                    <ThemedText className="font-semibold">Share PDF</ThemedText>
                                </Pressable>
                                <Pressable
                                    className="flex-1 flex-row items-center justify-center gap-2 rounded-2xl bg-gray-100 py-3"
                                    onPress={() => handleStatusReport('save')}>
                                    <MaterialIcons name="save-alt" size={18} color="#111827" />
                                    <ThemedText className="font-semibold">Save PDF</ThemedText>
                                </Pressable>
                            </View>
                        </View>
                    </View>
                </ScrollView>
            </SafeAreaView>
        </ThemedView>
    );
}

